import { useAuthContext } from "@/components/auth/AuthContext";
import { Button, Typography } from "@mui/material";
import { Box, Container } from "@mui/system";
import Head from "next/head";
export default function Home() {
  const { user } = useAuthContext();
  console.log(user);
  return (
    <>
      <Head>
        <title>Futsal Online Booking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Box sx={{ marginTop: 3 }}>
            <Typography variant="h1">
              Welcome to Futsal Online Booking
            </Typography>
            <Box sx={{ display: "flex", gap: 2 }}>
              <Button variant="outlined" size="large" href="/login">
                Login
              </Button>
              <Button variant="outlined" size="large" href="/register">
                Register
              </Button>
            </Box>
          </Box>
        </Container>
      </main>
    </>
  );
}
